# Usa la imagen oficial de PostgreSQL como base
FROM postgres:latest

# Variables de entorno para configurar el usuario y la contraseña de la base de datos
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=mypassword

# Variables de entorno para configurar la base de datos predeterminada y la codificación de caracteres
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_ENCODING=UTF8

# Expone el puerto predeterminado de PostgreSQL
EXPOSE 5432
