name: Test and Coverage

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "FLASK_ENV=development" >> $GITHUB_ENV
        echo "DATABASE_URI=postgresql://postgres:mypassword@postgres:5432/mydatabase" >> $GITHUB_ENV

    - name: Run tests
      run: pytest

  coverage:
    name: Measure Coverage
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report -m
