name: Test and Coverage

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "FLASK_ENV=development" >> $GITHUB_ENV
        echo "DATABASE_URI=postgresql://postgres:mypassword@localhost:5432" >> $GITHUB_ENV

    - name: Run tests
      run: pytest

  coverage:
    name: Measure Coverage
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report -m
